//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3_Idiots
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flag
    {
        public int flagID { get; set; }
        public Nullable<int> userID { get; set; }
        public string flag1 { get; set; }
    
        public virtual userTable userTable { get; set; }
    }
}
